name: 'Emily McBrayer '
favicon: null
layout_spectrum: 0.00103
typography_spectrum: 0.89085
title: 'Emily McBrayer, Business Coach for Wellness & Beauty Professionals'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1024'
    - '#e5d6d6'
    - '#cdb7b5'
    - '#8b7373'
    - '#87a0b4'
  brandStrength: 0.11752793076448143
  lightness: 0.875
  saturation: 0.5539945152122527
  rhythmicContrast: 0.13432630593888462
purpose: []
